### ISSUE TITLE
mgrpages/mgrusers.html

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#21]
## General Page Idea
Manager pages user management
This page will allow the manager role to edit, disable, create accounts. 

## General Layout
* a Button to create a new user
* the ability to filter the grid.
* The ability for a manager to edit any reservation 
* Edit/new button will use the same modal form to input the information for the user account. 
* Delete won't delete rather flip a bit to inactive (might need a report of inactive accounts eventually to allow a manager to re-activate)

## Example Grid
|Edit|Last Name|First Name|Status|Role|Delete|
|---|---|---|---|---|---|
|Edit Button|Last|First|Locked|Manager|Delete Button|
|Edit Button|Last|First|Active|Employee|Delete Button|
|Edit Button|Last|First|deactviated|Employee|Delete Button|
|Edit Button|Last|First|Active|User|Delete Button|

## Task List
- [x] Grid on page
- [x] button in grid
- [x] modal built
- [x] modal populated with html
- [x] controller setup to pull data from Mongo to fill in grid
- [x] controller setup to pull data to fill in modal form
- [x] Modal submit button wired to Create User function . 
- [x] Modal submit button wired to Update User function . 
- [x] Modal submit button wired to Delete User function .

**Comment by ghost** [comment]
User page is complete.
