### ISSUE TITLE
Reservations.html

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#4]
## General Page Idea
This page should support a grid of all the reservations with the capacity to edit the reservations within the grid. 
Additional items on this page should include the capacity to filter the table and create a new reservation (over the phone as an example) 

## Example Grid
|Name|Check-in Date|Check-out Date|Edit|
|---|---|---|---|
|Last, First|dd/mmm/yyyy|dd/mmm/yyyy|<button>|
|Last, First|dd/mmm/yyyy|dd/mmm/yyyy|<button>|

## Task List
- [x] Grid on page
- [x] button in grid
- [x] modal built
- [x] modal populated with html
- [x] controller setup to pull data from Mongo to fill in grid
- [x] controller setup to pull data to fill in modal form
- [x] submit button wired to Create Reservation function. 
- [x] Flash that Reservation was created
