### ISSUE TITLE
Checkin.html

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#5]
## General Page Idea
This page should support a grid of all the check-ins that are occurring that day. with the capacity to add a walk-in without a reservation within the grid. 
Additional items on this page should include the capacity to filter the table and create a new reservation walk in, once the button has been clicked we should display their information to the clerk so that they can update any information and collect their card number if needed.  A confirmation screen should appear after submission and the user should receive an email.  

## Example Grid
|Name|Check-in Date|Check-out Date|Check-in Action|
|---|---|---|---|
|Last, First|dd/mmm/yyyy|dd/mmm/yyyy|Button|
|Last, First|dd/mmm/yyyy|dd/mmm/yyyy|button|

## Task List
- [x] Grid on page
- [x] button in grid
- [x] modal built
- [x] modal populated with html
- [x] controller setup to pull data from Mongo to fill in grid
- [x] controller setup to pull data to fill in modal form
- [x] submit button wired to checkin function. 
- [x] Flash that Check in was complete

**Comment by ghost** [comment]
@rcarle3911, @jmoore4 Having an issue with the tabs in the modal window. 
The tabs are on the page and wired up to load: 
* /emp/pages/modalCheckin.html 
* emp/pages/modalhistory.html

When the page modal window initially loads the default page should be check-in but it isn't loading on the initial load. When you click on "Check in" Tab it will load the content from the HTML page. 

We can hard code the check-in tab HTML in checkin.html and not use a separate HTML page to house this content. I'd like to use a separate history page since it will be used elsewhere in the app. 

If you guys can take a peek at the JavaScript /emp/pages/checkin.modal.js and see if there is something that doesn't jive

```JavaScript
$('#modalTabs a').click(function (e) {
	e.preventDefault();
  
	var url = $(this).attr("data-url");
  	var href = this.hash;
  	var pane = $(this);
	
	// ajax load from data-url
	$(href).load(url,function(result){      
	    pane.tab('show');
	});
});

// load first tab content
$('#ModalCheckIn').load($('.active a').attr("data-url"),function(result){
  $('.active a').tab('show');
});
```

**Comment by rcarle3911** [comment]
The issue happens in 
```JavaScript 
$('#ModalCheckIn').load
``` 
.... it loads based on the class "active" and the element a. The main view and the model view share those classes. If you change the modal class to "activeM" and load it based on that, your issue goes away. If you need still need the class to be "active" you can add a third class to differentiate between the main/modal views.
